apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: crdp
  name: crdp-deployment
spec:
  template:
     metadata:
        name: crdp
        labels:
          run: crdp
     spec:
      containers:
        - image: thalesciphertrust/ciphertrust-restful-data-protection:latest
          imagePullPolicy: IfNotPresent
          name: crdp
          env:
            - name: KEY_MANAGER_HOST
              valueFrom:
                configMapKeyRef:
                  name: crdp-config
                  key: CM_HOST
            - name: SERVER_MODE
              valueFrom:
                configMapKeyRef:
                  name: crdp-config
                  key:  TLS_MODE
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: crdp-reg-token
                  key: regtoken

  replicas: 1
  selector:
      matchLabels:
        run: crdp