apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kust

resources:
  - crdp-dep.yaml
  - crdp-svc.yaml
  - reg-token.yaml

configMapGenerator:
- name: crdp-config
  literals:
  - TLS_MODE=no-tls
  - CM_HOST=cm-ninja.kiukairor.com