apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kust

resources:
  - crdp-dep.yaml
  - crdp-svc.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: crdp-config
  literals:
  - TLS_MODE=no-tls                 # no-tls, tls-cert-opt, tsl-cert
  - CM_HOST=cm-ninja.kiukairor.com  # Modify here to your hostname/IP for CipherTrust

secretGenerator:
  - name: crdp-reg-token
    type: Opaque
    files:
      - regtoken=regtoken/value